/* ============================================================
   ANTISTAR-moviMIENTO — signal data
   GLOBAL DIAL: 101 verified relays + 30 ALT-WAVE underground stations = 131 feeds,
   mounted as 140 channels across 80 countries
   (HTTP 200 + open CORS + rolling segments / flowing audio bytes,
   verified 2026-09 against iptv-org + radio-browser community data)
   swap for a real backend / P2P layer later
   ============================================================ */

const LIVE_FEEDS = [
  {
    id: "rbtv",
    label: "RELAY-01 · RED BULL TV",
    url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    kind: "hls",
  },
  {
    id: "dw",
    label: "RELAY-02 · DW",
    url: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
    kind: "hls",
  },
  {
    id: "trt",
    label: "RELAY-03 · TRT WORLD",
    url: "https://tv-trtworld.medya.trt.com.tr/master.m3u8",
    kind: "hls",
  },
  {
    id: "cbsn",
    label: "RELAY-04 · CBS NEWS",
    url: "https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8",
    kind: "hls",
  },
];

/* archived VOD for replay channels — verified 200 + open CORS
   liveVod marks these as looping archives so the player treats them honestly */
const ARCHIVE_STREAMS = [
  {
    id: "mux-bunny",
    label: "ARCHIVE NODE · MUX",
    url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    kind: "hls",
    liveVod: true,
  },
  {
    id: "mux-pts",
    label: "ARCHIVE NODE · MUX",
    url: "https://test-streams.mux.dev/pts_shift/master.m3u8",
    kind: "hls",
    liveVod: true,
  },
];

/* ---- the global dial ----
   kind:"hls" = video HLS · kind:"radio" = continuous audio stream
   cat: general|news|culture|music|community|access|legislative|outdoor|weather */
const GLOBAL_FEEDS = [
  /* ── LATINOAMÉRICA · TV ─────────────────────────────── */
  { id:"g-ar-santafe", cc:"AR", kind:"hls", cat:"general", label:"AR · AIRE DE SANTA FE", url:"https://unlimited1-us.dps.live/airedesantafetv/airedesantafetv.smil/playlist.m3u8" },
  { id:"g-bo-audiokiss", cc:"BO", kind:"hls", cat:"music", label:"BO · AUDIOKISS TV", url:"https://master.tucableip.com/audiokisstv/index.m3u8" },
  { id:"g-cl-13c", cc:"CL", kind:"hls", cat:"culture", label:"CL · 13C CULTURA", url:"https://origin.dpsgo.com/ssai/event/GI-9cp_bT8KcerLpZwkuhw/master.m3u8" },
  { id:"g-cr-agrotendencia", cc:"CR", kind:"hls", cat:"outdoor", label:"CR · AGROTENDENCIA", url:"https://5fc584f3f19c9.streamlock.net/agrotendencia/videoagrotendencia_hls1/playlist.m3u8" },
  { id:"g-cu-prensalatina", cc:"CU", kind:"hls", cat:"news", label:"CU · PRENSA LATINA TV", url:"https://eu1.servers10.com:8081/8192/index.m3u8" },
  { id:"g-do-a7", cc:"DO", kind:"hls", cat:"general", label:"DO · A7 TV JARABACOA", url:"https://183.bozztv.com/ssh101/ssh101/a7tvjarabacoa/playlist.m3u8" },
  { id:"g-ec-austral", cc:"EC", kind:"hls", cat:"general", label:"EC · AUSTRAL TV", url:"https://stmv3.voxtvhd.com.br/australtv/australtv/playlist.m3u8" },
  { id:"g-gt-barbe", cc:"GT", kind:"hls", cat:"general", label:"GT · BARBE TV", url:"https://cdn.streamhispanatv.net:3549/live/barbetvlive.m3u8" },
  { id:"g-hn-aza", cc:"HN", kind:"hls", cat:"general", label:"HN · AZA TV HD", url:"https://tv.webmedialive.com/azatvhn/live/playlist.m3u8" },
  { id:"g-mx-b15", cc:"MX", kind:"hls", cat:"general", label:"MX · B15 FRESNILLO", url:"https://s5.mexside.net:1936/lsac/lsac/playlist.m3u8" },
  { id:"g-pe-genios", cc:"PE", kind:"hls", cat:"general", label:"PE · GENIOS TV", url:"https://sc3.wasidata.com/Genios2_1902/video.m3u8" },
  { id:"g-pr-amteve", cc:"PR", kind:"hls", cat:"general", label:"PR · AMERICA TEVE", url:"https://live.gideo.video/americateve2/master.m3u8" },
  { id:"g-uy-canalu", cc:"UY", kind:"hls", cat:"culture", label:"UY · CANAL U", url:"https://livedelta.cdn.antel.net.uy/out/u/url_canalu.m3u8" },
  /* ── LATINOAMÉRICA · RADIO ──────────────────────────── */
  { id:"r-ar-rivadavia", cc:"AR", kind:"radio", cat:"news", label:"AR · RADIO RIVADAVIA", url:"https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIA.mp3" },
  { id:"r-br-saudade", cc:"BR", kind:"radio", cat:"music", label:"BR · RÁDIO SAUDADE FM", url:"https://playerservices.streamtheworld.com/api/livestream-redirect/SAUDADE_FMAAC.aac" },
  { id:"r-co-olimpica", cc:"CO", kind:"radio", cat:"music", label:"CO · OLÍMPICA STEREO", url:"https://playerservices.streamtheworld.com/api/livestream-redirect/OLP_MEDELLINAAC.aac" },
  { id:"r-gt-emisoras", cc:"GT", kind:"radio", cat:"news", label:"GT · EMISORAS UNIDAS", url:"https://stream.zenolive.com/z96sq8tndseuv" },
  { id:"r-hn-hrn", cc:"HN", kind:"radio", cat:"news", label:"HN · HRN LA VOZ", url:"https://ice42.securenetsystems.net/HRN" },
  { id:"r-mx-caferomantico", cc:"MX", kind:"radio", cat:"music", label:"MX · CAFÉ ROMÁNTICO", url:"https://panel.retrolandigital.com/radio/8110/listen" },
  { id:"r-pa-planet", cc:"PA", kind:"hls", cat:"music", label:"PA · PLANET 100.9", url:"https://streamlov.alsolnet.com/planet1009fm/live/playlist.m3u8" },

  /* ── ÁFRICA · TV ────────────────────────────────────── */
  { id:"g-dz-al24", cc:"DZ", kind:"hls", cat:"news", label:"DZ · AL24 NEWS", url:"https://cdn.live.easybroadcast.io/abr_corp/66_al24_u4yga6h/corp/66_al24_u4yga6h_240p/chunks.m3u8" },
  { id:"g-bf-filinfo", cc:"BF", kind:"hls", cat:"news", label:"BF · FILINFO TV", url:"https://d2iqjnqfr8pv3b.cloudfront.net/out/v1/d09d2fc718404cd8bccd3eba2444dd70/index.m3u8" },
  { id:"g-cm-cam10", cc:"CM", kind:"hls", cat:"general", label:"CM · CAM 10 TV", url:"https://stream.it-innov.com/cam10tv/index.m3u8" },
  { id:"g-eg-alghad", cc:"EG", kind:"hls", cat:"news", label:"EG · AL GHAD TV", url:"https://eazyvwqssi.erbvr.com/alghadtv/alghadtv.m3u8" },
  { id:"g-ke-k24", cc:"KE", kind:"hls", cat:"general", label:"KE · K24 TV", url:"https://livecdn.premiumfree.tv/afxpstr/K24Backup/index.m3u8" },
  { id:"g-ma-2m", cc:"MA", kind:"hls", cat:"general", label:"MA · 2M MONDE", url:"https://d2qh3gh0k5vp3v.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-n6pess5lwbghr/2M_ES.m3u8" },
  { id:"g-mz-tvm", cc:"MZ", kind:"hls", cat:"general", label:"MZ · TVM MOZAMBIQUE", url:"https://stream.tvm.co.mz/hls/tvm/playlist.m3u8" },
  { id:"g-ng-nigbati", cc:"NG", kind:"hls", cat:"culture", label:"NG · NIGBATI TV", url:"https://viewmedia7219.bozztv.com/wmedia/viewmedia100/web_023/Stream/playlist.m3u8" },
  { id:"g-rw-tv10", cc:"RW", kind:"hls", cat:"general", label:"RW · TV10 KIGALI", url:"https://5c46fa289c89f.streamlock.net/pub1live/mystream/playlist.m3u8" },
  { id:"g-td-tchad", cc:"TD", kind:"hls", cat:"general", label:"TD · TÉLÉ TCHAD", url:"https://strhlslb01.streamakaci.tv/str_tchad_tchad/str_tchad_multi/playlist.m3u8" },
  { id:"g-ug-tayari", cc:"UG", kind:"hls", cat:"general", label:"UG · TAYARI WEST TV", url:"https://stream.hydeinnovations.com/tarari-west/index.m3u8" },
  { id:"g-za-ln24", cc:"ZA", kind:"hls", cat:"news", label:"ZA · LN24 SA", url:"https://cdnstack.internetmultimediaonline.org/ln24/ln24.stream/playlist.m3u8" },
  /* ── ÁFRICA · RADIO ─────────────────────────────────── */
  { id:"r-et-sheger", cc:"ET", kind:"radio", cat:"general", label:"ET · SHEGER FM 102.1", url:"https://stream.zenolive.com/y91n1vtbaw5tv" },
  { id:"r-gh-citi", cc:"GH", kind:"radio", cat:"news", label:"GH · CITI FM 97.3", url:"https://citi973fm.radioca.st/stream" },
  { id:"r-ma-hitradio", cc:"MA", kind:"radio", cat:"music", label:"MA · HIT RADIO", url:"https://stream.zeno.fm/une3a02mb" },
  { id:"r-mw-zodiak", cc:"MW", kind:"radio", cat:"news", label:"MW · ZODIAK FM", url:"https://ice31.securenetsystems.net/0079" },
  { id:"r-tz-eastafrica", cc:"TZ", kind:"radio", cat:"general", label:"TZ · EAST AFRICA RADIO", url:"https://eatv.radioca.st/stream" },
  { id:"r-ug-djs", cc:"UG", kind:"radio", cat:"music", label:"UG · UGANDA DJS", url:"https://stream.zeno.fm/muzrp86994zuv" },
  { id:"r-za-jacaranda", cc:"ZA", kind:"radio", cat:"news", label:"ZA · JACARANDA FM", url:"https://edge.iono.fm/xice/jacarandafm_live_medium.aac" },

  /* ── ASIA · TV ──────────────────────────────────────── */
  { id:"g-bd-rajhani", cc:"BD", kind:"hls", cat:"general", label:"BD · RAJDHANI TV", url:"https://stream.shariarsuvo.com/hls5/rajdhanicable.m3u8" },
  { id:"g-kh-ardb", cc:"KH", kind:"hls", cat:"outdoor", label:"KH · ARDB TV", url:"https://ardbtv.ardb.com.kh:8443/tv-live/tv-online.m3u8" },
  { id:"g-mm-dvb", cc:"MM", kind:"hls", cat:"news", label:"MM · DVB TV", url:"https://live-stream.dvb.no/hls/stream_src/index.m3u8" },
  { id:"g-np-kantipur", cc:"NP", kind:"hls", cat:"general", label:"NP · KANTIPUR TV HD", url:"https://ktvhdsg.ekantipur.com:8443/high_quality_85840165/hd/playlist.m3u8" },
  { id:"g-ph-bilyonaryo", cc:"PH", kind:"hls", cat:"news", label:"PH · BILYONARYO NEWS", url:"https://amg19223-amg19223c11-amgplt0352.playout.now3.amagi.tv/playlist/amg19223-amg19223c11-amgplt0352/playlist.m3u8" },
  { id:"g-sg-cna", cc:"SG", kind:"hls", cat:"news", label:"SG · CNA", url:"https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index.m3u8" },
  { id:"g-th-siam13", cc:"TH", kind:"hls", cat:"news", label:"TH · 13 SIAM THAI", url:"https://live.x2.co.th/live/13livetv-th.m3u8" },
  { id:"g-uz-dunyo", cc:"UZ", kind:"hls", cat:"general", label:"UZ · DUNYO BO'YLAB", url:"https://stream8.cinerama.uz/1006/tracks-v1a1/playlist.m3u8" },
  { id:"g-vn-cantho", cc:"VN", kind:"hls", cat:"general", label:"VN · CẦN THƠ TV", url:"https://live.canthotv.vn/live/tv/chunklist.m3u8" },
  { id:"g-kr-arirang", cc:"KR", kind:"hls", cat:"news", label:"KR · ARIRANG UN", url:"https://amdlive-ch02-ctnd-com.akamaized.net/arirang_2ch/smil:arirang_2ch.smil/playlist.m3u8" },
  { id:"g-kr-gugak", cc:"KR", kind:"hls", cat:"music", label:"KR · GUGAK TV", url:"https://mgugaklive.nowcdn.co.kr/gugakvideo/gugakvideo.stream/playlist.m3u8" },
  /* ── ASIA · RADIO ───────────────────────────────────── */
  { id:"r-bd-a2z", cc:"BD", kind:"radio", cat:"general", label:"BD · A2Z RADIO", url:"https://listen.radioking.com/radio/1743/stream/125" },
  { id:"r-id-elshinta", cc:"ID", kind:"radio", cat:"news", label:"ID · ELSHINTA JAKARTA", url:"https://stream-ssl.arenastreaming.com:8000/jakarta" },
  { id:"r-kz-eurodance", cc:"KZ", kind:"radio", cat:"music", label:"KZ · RADIO 90S EURODANCE", url:"https://listen1.myradio24.com/5967" },
  { id:"r-mm-mandalay", cc:"MM", kind:"radio", cat:"general", label:"MM · MANDALAY FM", url:"https://edge.mixlr.com/channel/nmtev" },
  { id:"r-my-slowrock", cc:"MY", kind:"radio", cat:"music", label:"MY · SLOW ROCK 90S", url:"https://stream.zeno.fm/hiut6cwfoneuv" },
  { id:"r-ph-starfm", cc:"PH", kind:"radio", cat:"music", label:"PH · STAR FM MANILA", url:"https://stream-13.zeno.fm/g1pmt17nz9duv" },
  { id:"r-pk-samaa", cc:"PK", kind:"radio", cat:"news", label:"PK · SAMAA FM 107.4", url:"https://samaakhi107-itelservices.radioca.st/stream" },
  { id:"r-vn-rfi", cc:"VN", kind:"radio", cat:"news", label:"VN · RFI TIẾNG VIỆT", url:"https://rfienvietnamien64k.ice.infomaniak.ch/rfienvietnamien-64.mp3" },

  /* ── MEDIO ORIENTE · TV ─────────────────────────────── */
  { id:"g-iq-rasheed", cc:"IQ", kind:"hls", cat:"general", label:"IQ · AL RASHEED TV", url:"https://media1.livaat.com/static/AL-RASHEED-HD/playlist.m3u8" },
  { id:"g-kw-ktv1", cc:"KW", kind:"hls", cat:"general", label:"KW · KTV 1", url:"https://kwtktv1ta.cdn.mangomolo.com/ktv1/smil:ktv1.stream.smil/chunklist.m3u8" },
  { id:"g-lb-aghani", cc:"LB", kind:"hls", cat:"music", label:"LB · AGHANI AGHANI TV", url:"https://cdn.streamlane.tv/hls/aghanitv/index.m3u8" },
  { id:"g-ps-najah", cc:"PS", kind:"hls", cat:"news", label:"PS · AL NAJAH NEWS", url:"https://streaming.najah.edu:8443/hls/AlNajah.m3u8" },
  { id:"g-qa-alaraby", cc:"QA", kind:"hls", cat:"news", label:"QA · AL ARABY TV", url:"https://live.kwikmotion.com/alaraby1live/alaraby_abr/playlist.m3u8" },
  { id:"g-sa-arabiya", cc:"SA", kind:"hls", cat:"news", label:"SA · AL ARABIYA ENGLISH", url:"https://live.alarabiya.net/alarabiapublish/english/playlist_dvr.m3u8" },
  { id:"g-tr-trtgenc", cc:"TR", kind:"hls", cat:"culture", label:"TR · TRT GENÇ", url:"https://tv-trtgenc.medya.trt.com.tr/master.m3u8" },
  { id:"g-ye-masirah", cc:"YE", kind:"hls", cat:"news", label:"YE · AL MASIRAH TV", url:"https://live.cdnbridge.tv/Almasirah/Almasirah_all/playlist.m3u8" },
  /* ── MEDIO ORIENTE · RADIO ──────────────────────────── */
  { id:"r-ge-amra", cc:"GE", kind:"radio", cat:"music", label:"GE · RADIO AMRA", url:"https://streamer.radio.co/s34b5469e0/listen" },
  { id:"r-iq-sumer", cc:"IQ", kind:"radio", cat:"music", label:"IQ · SUMER FM", url:"https://l3.itworkscdn.net/itwaudio/9012/stream" },
  { id:"r-jo-mazaj", cc:"JO", kind:"radio", cat:"music", label:"JO · MAZAJ FM", url:"https://mazajfm.ice.infomaniak.ch/mazajfm-192.mp3" },
  { id:"r-lb-sawtlebnan", cc:"LB", kind:"radio", cat:"general", label:"LB · VOICE OF LEBANON", url:"https://l3.itworkscdn.net/itwaudio/9054/stream" },

  /* ── EUROPA · TV ────────────────────────────────────── */
  { id:"g-be-atv", cc:"BE", kind:"hls", cat:"general", label:"BE · ATV ANTWERPEN", url:"https://live.zendzend.com/mpegts/29375_107244/media_mpegts_0.m3u8" },
  { id:"g-cz-currenttime", cc:"CZ", kind:"hls", cat:"news", label:"CZ · CURRENT TIME TV", url:"https://rfe-ingest.akamaized.net/hls/live/2033043/tvmc05/master.m3u8" },
  { id:"g-dk-dr1", cc:"DK", kind:"hls", cat:"general", label:"DK · DR1", url:"https://drlivedr1hls.akamaized.net/hls/live/2113625/drlivedr1/master.m3u8" },
  { id:"g-fi-nopola", cc:"FI", kind:"hls", cat:"news", label:"FI · NOPOLA NEWS", url:"https://virta2.nopolanews.fi:8443/live/smil:Stream1.smil/playlist.m3u8" },
  { id:"g-fr-20min", cc:"FR", kind:"hls", cat:"general", label:"FR · 20 MINUTES TV", url:"https://live-20minutestv.digiteka.com/1961167769/index.m3u8" },
  { id:"g-gr-alpha", cc:"GR", kind:"hls", cat:"general", label:"GR · ALPHA TV", url:"https://alphatvlive2.siliconweb.com/alphatvlive/live_abr/playlist.m3u8" },
  { id:"g-hr-cmc", cc:"HR", kind:"hls", cat:"music", label:"HR · CMC TV", url:"https://stream.cmctv.hr:49998/cmc/live.m3u8" },
  { id:"g-nl-twente", cc:"NL", kind:"hls", cat:"general", label:"NL · 1TWENTE TV", url:"https://ms7.mx-cd.net/dtv-11/198-989148/1Twente_TV.smil/chunklist_w954512639_b4292608_slNLD.m3u8" },
  { id:"g-no-ostfold", cc:"NO", kind:"hls", cat:"general", label:"NO · TV ØSTFOLD", url:"https://streamnorge.com:8088/hls/tvo.m3u8" },
  { id:"g-pt-artv", cc:"PT", kind:"hls", cat:"legislative", label:"PT · ARTV PARLAMENTO", url:"https://playout172.livextend.cloud/liveiframe/_definst_/liveartvabr/playlist.m3u8" },
  { id:"g-ro-a7tv", cc:"RO", kind:"hls", cat:"general", label:"RO · A7TV", url:"https://a7tvlive.ro/A7TV/A7TV/playlist.m3u8" },
  { id:"g-se-ditv", cc:"SE", kind:"hls", cat:"news", label:"SE · DI TV", url:"https://cdn0-03837-liveedge0.dna.ip-only.net/03837-liveedge0/smil:03837-tx4/playlist.m3u8" },
  /* ── EUROPA · RADIO ─────────────────────────────────── */
  { id:"r-cz-svoboda", cc:"CZ", kind:"hls", cat:"news", label:"CZ · РАДИО СВОБОДА", url:"https://rfe-ingest.akamaized.net/hls/live/2035254/axia04/playlist.m3u8" },
  { id:"r-es-los40", cc:"ES", kind:"radio", cat:"music", label:"ES · LOS40 ESPAÑA", url:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40.mp3" },
  { id:"r-gr-zeppelin", cc:"GR", kind:"radio", cat:"music", label:"GR · ZEPPELIN 106.7", url:"https://radiostreaming.ert.gr/ert-zeppelin" },
  { id:"r-hu-dancewave", cc:"HU", kind:"radio", cat:"music", label:"HU · DANCE WAVE!", url:"https://dancewave.online/dance.mp3" },
  { id:"r-pt-rfm", cc:"PT", kind:"radio", cat:"music", label:"PT · RFM", url:"https://23603.live.streamtheworld.com/RFMAAC.aac" },
  { id:"r-ru-vanya", cc:"RU", kind:"radio", cat:"music", label:"RU · РАДИО ВАНЯ", url:"https://icecast-radiovanya.cdnvideo.ru/radiovanya" },

  /* ── NORTeamérica ───────────────────────────────────── */
  { id:"g-us-accuweather", cc:"US", kind:"hls", cat:"weather", label:"US · ACCUWEATHER NOW", url:"https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg00684-accuweather-accuweather-plex/playlist.m3u8" },
  { id:"g-us-akaku53", cc:"US", kind:"hls", cat:"access", label:"US · AKAKU 53 MAUI", url:"https://castus-vod-dev.s3.amazonaws.com/vod_clients/akaku/live/ch1/video.m3u8" },
  { id:"g-us-akaku55", cc:"US", kind:"hls", cat:"access", label:"US · AKAKU 55 MAUI", url:"https://castus-vod-dev.s3.amazonaws.com/vod_clients/akaku/live/ch3/video.m3u8" },
  { id:"g-us-aftv", cc:"US", kind:"hls", cat:"access", label:"US · AFTV FRAMINGHAM", url:"https://livestream.telvue.com/accframingham1/f7b44cfafd5c52223d5498196c8a2e7b.sdp/playlist.m3u8" },
  { id:"g-ca-azstar", cc:"CA", kind:"hls", cat:"general", label:"CA · AZ STAR TV", url:"https://live.livestreamtv.ca/azstar/amlst:azstar/playlist.m3u8" },
  { id:"r-ca-cfru", cc:"CA", kind:"radio", cat:"community", label:"CA · CFRU 93.3 GUELPH", url:"https://s2.cfru.ca:8443/stream" },
  { id:"r-us-kgnu", cc:"US", kind:"radio", cat:"community", label:"US · KGNU 88.5 BOULDER", url:"https://kgnu-stream1.colorado.net/kgnu" },
  { id:"r-us-wfmu", cc:"US", kind:"radio", cat:"community", label:"US · WFMU 91.1 FREEFORM", url:"https://stream0.wfmu.org/freeform-128k" },

  /* ── OCEANÍA ────────────────────────────────────────── */
  { id:"g-au-abcnews", cc:"AU", kind:"hls", cat:"news", label:"AU · ABC NEWS", url:"https://abc-news-dmd-streams-1.akamaized.net/out/v1/701126012d044971b3fa89406a440133/index.m3u8" },
  { id:"g-au-ticker", cc:"AU", kind:"hls", cat:"news", label:"AU · TICKER NEWS", url:"https://live-hls-7agy.livepush.io/live_abr_cdn/nsitWAl1pTZtwca/emnmZbKZcO8RfwJR/index.m3u8" },
  { id:"g-nz-parliament", cc:"NZ", kind:"hls", cat:"legislative", label:"NZ · PARLIAMENT TV", url:"https://ptvlive.kordia.net.nz/out/v1/daf20b9a9ec5449dadd734e50ce52b74/index.m3u8" },
  { id:"g-pg-nbc", cc:"PG", kind:"hls", cat:"general", label:"PG · NBC TV PNG", url:"https://205444.global.ssl.fastly.net/64ee8a084b935f9f8a6f8825/live_ab333a6093bc11eeb89fbd81423485b7/index.fmp4.m3u8" },
  { id:"r-au-3cr", cc:"AU", kind:"radio", cat:"community", label:"AU · 3CR 855AM MELBOURNE", url:"https://s1.mediacast.io/3cr-stream/mp3-128/" },
];

/* ISO2 → display name for every country on the dial */
const COUNTRY_NAMES = {
  AR:"Argentina", BO:"Bolivia", BR:"Brazil", CL:"Chile", CO:"Colombia", CR:"Costa Rica",
  CU:"Cuba", DO:"Dominican Rep.", EC:"Ecuador", GT:"Guatemala", HN:"Honduras", MX:"Mexico",
  PA:"Panama", PE:"Peru", PR:"Puerto Rico", UY:"Uruguay",
  DZ:"Algeria", BF:"Burkina Faso", CM:"Cameroon", EG:"Egypt", ET:"Ethiopia", GH:"Ghana",
  KE:"Kenya", MA:"Morocco", MW:"Malawi", MZ:"Mozambique", NG:"Nigeria", RW:"Rwanda",
  TD:"Chad", TZ:"Tanzania", UG:"Uganda", ZA:"South Africa",
  BD:"Bangladesh", ID:"Indonesia", KH:"Cambodia", KR:"South Korea", KZ:"Kazakhstan",
  MM:"Myanmar", MY:"Malaysia", NP:"Nepal", PH:"Philippines", PK:"Pakistan", SG:"Singapore",
  TH:"Thailand", UZ:"Uzbekistan", VN:"Vietnam",
  GE:"Georgia", IQ:"Iraq", JO:"Jordan", KW:"Kuwait", LB:"Lebanon", PS:"Palestine",
  QA:"Qatar", SA:"Saudi Arabia", TR:"Türkiye", YE:"Yemen",
  BE:"Belgium", CZ:"Czechia", DK:"Denmark", ES:"Spain", FI:"Finland", FR:"France",
  GR:"Greece", HU:"Hungary", HR:"Croatia", NL:"Netherlands", NO:"Norway", PT:"Portugal",
  RO:"Romania", RU:"Russia", SE:"Sweden",
  CA:"Canada", US:"United States",
  AT:"Austria", SI:"Slovenia",
  AU:"Australia", NZ:"New Zealand", PG:"Papua New Guinea",
};

/* original barrio channels — the founding transmitters */
const ORIGINAL_CHANNELS = [
  {
    id: "ch-001",
    slug: "la-voz-del-block",
    title: "LA VOZ DEL BLOQUE — asamblea abierta",
    host: "colectivo_voz",
    tags: ["asamblea", "es", "24/7"],
    live: true,
    viewers: 4812,
    stream: LIVE_FEEDS[0],
    thumb: "https://picsum.photos/seed/antistar01/640/360",
    started: Date.now() - 1000 * 60 * 62,
    desc: "Micrófono abierto del barrio. Decisiones en vivo, sin moderación de arriba hacia abajo.",
  },
  {
    id: "ch-002",
    slug: "static-hymns",
    title: "STATIC HYMNS — basement noise set",
    host: "dead.freq",
    tags: ["noise", "music", "en"],
    live: true,
    viewers: 1290,
    stream: LIVE_FEEDS[1],
    thumb: "https://picsum.photos/seed/antistar02/640/360",
    started: Date.now() - 1000 * 60 * 27,
    desc: "Synths soldered by hand, feedback loops until the amp surrenders.",
  },
  {
    id: "ch-003",
    slug: "kitchen-table-history",
    title: "HISTORIA EN LA MESA — archivo militante",
    host: "archiva.lat",
    tags: ["historia", "es"],
    live: false,
    viewers: 0,
    stream: ARCHIVE_STREAMS[0],
    thumb: "https://picsum.photos/seed/antistar03/640/360",
    started: Date.now() - 1000 * 60 * 60 * 19,
    duration: 3 * 3600 + 41 * 60,
    desc: "Cápsulas de historia popular desde la cocina de la abuela. Repetición del pasado domingo.",
  },
  {
    id: "ch-004",
    slug: "rooftop-cinema",
    title: "ROOFTOP CINEMA — pirated classics night",
    host: "celluloid_riot",
    tags: ["cine", "en"],
    live: true,
    viewers: 7455,
    stream: LIVE_FEEDS[3],
    thumb: "https://picsum.photos/seed/antistar04/640/360",
    started: Date.now() - 1000 * 60 * 133,
    desc: "One projector, one bedsheet, forty strangers. Tonight: early Jodorowsky shorts.",
  },
  {
    id: "ch-005",
    slug: "antena-libre",
    title: "ANTENA LIBRE — taller de radio pirata",
    host: "onda_negra",
    tags: ["radio", "taller", "es"],
    live: false,
    viewers: 0,
    stream: ARCHIVE_STREAMS[1],
    thumb: "https://picsum.photos/seed/antistar05/640/360",
    started: Date.now() - 1000 * 60 * 60 * 40,
    duration: 2 * 3600 + 5 * 60,
    desc: "Cómo construir un transmisor FM con $14 y consecuencias.",
  },
  {
    id: "ch-006",
    slug: "the-wire-mothership",
    title: "WIRE/ALPHA — mesh network status room",
    host: "n0de_7",
    tags: ["mesh", "tech", "en"],
    live: true,
    viewers: 613,
    stream: LIVE_FEEDS[2],
    thumb: "https://picsum.photos/seed/antistar06/640/360",
    started: Date.now() - 1000 * 60 * 8,
    desc: "Live telemetry from the community mesh. Bring routers, leave passwords.",
  },
  {
    id: "ch-007",
    slug: "cocina-colectiva",
    title: "COCINA COLECTIVA — ollas para 300",
    host: "olla_popular",
    tags: ["comida", "es", "mutual aid"],
    live: true,
    viewers: 2230,
    stream: LIVE_FEEDS[1],
    thumb: "https://picsum.photos/seed/antistar07/640/360",
    started: Date.now() - 1000 * 60 * 45,
    desc: "Cocinamos para la marcha de mañana. Lista de lo que falta en el chat fijado.",
  },
  {
    id: "ch-008",
    slug: "neon-vigil",
    title: "NEON VIGIL — ambient against forgetting",
    host: "luna_k",
    tags: ["ambient", "en"],
    live: false,
    viewers: 0,
    stream: ARCHIVE_STREAMS[0],
    thumb: "https://picsum.photos/seed/antistar08/640/360",
    started: Date.now() - 1000 * 60 * 60 * 30,
    duration: 5 * 3600 + 12 * 60,
    desc: "Six hours of drones for the memorial wall. Names read every hour.",
  },
  {
    id: "ch-009",
    slug: "pirate-physics",
    title: "PIRATE PHYSICS — antennas for the people",
    host: "prof_x_antena",
    tags: ["ciencia", "en", "taller"],
    live: true,
    viewers: 389,
    stream: LIVE_FEEDS[0],
    thumb: "https://picsum.photos/seed/antistar09/640/360",
    started: Date.now() - 1000 * 60 * 102,
    desc: "Why a cantenna beats a $300 router antenna. Math included, mercy not.",
  },
];
/* broadcast ticker */
const TICKER_ITEMS = [
  ["ALERTA", "repetidor norte en 91.3 FM vuelve al aire tras las lluvias"],
  ["MESH", "3 nuevos nodos enlazados esta noche"],
  ["CONVOCATORIA", "marcha 14h plaza central — transmití desde tu cuadra"],
  ["MANIFIESTO", "artículo 7: el espectro pertenece a quien lo camina"],
  ["MUTUAL AID", "olla colectiva necesita aceite y cebolla"],
  ["STAT", "moviMIENTO cruzó los 30k espectadores simultáneos"],
  ["DIAL GLOBAL", "80 países al aire: de Maui a Nablus, de Dar es Salaam a Tashkent"],
  ["ALT-WAVE", "30 emisoras libres: Pacifica, Rinse, Canut, Alhara — la contrafrecuencia"],
  ["AVISO", "ninguna estrella fue autorizada en la construcción de esta red"],
];

const BOOT_LINES = [
  "hailing frequency…",
  "negotiating with the spectrum",
  "scanning 80 countries of relay",
  "syncing <b>132</b> mesh nodes",
  "calibrating spite",
  "signal locked",
];

const G = (feed, o) => ({
  id: o.id,
  slug: o.slug,
  title: o.title,
  host: o.host,
  tags: o.tags,
  live: true,
  viewers: o.viewers,
  stream: feed,
  thumb: `https://picsum.photos/seed/${o.slug}/640/360`,
  started: Date.now() - o.mins * 60000,
  desc: o.desc,
  cc: feed.cc,
  country: COUNTRY_NAMES[feed.cc] || feed.cc,
});

const CHANNELS = [
  ...ORIGINAL_CHANNELS,

  /* ── LATINOAMÉRICA ──────────────────────────────────── */
  G(GLOBAL_FEEDS[0], { id:"ch-010", slug:"aire-de-santa-fe", title:"EL LITORAL EN VIVO — santa fe sin filtro", host:"litoral_libre", tags:["es","río","24/7"], viewers:842, mins:190, desc:"La costa del Paraná, la Feria, el debate de siempre. Televisión pública del litoral, al aire de todos." }),
  G(GLOBAL_FEEDS[1], { id:"ch-011", slug:"audiokiss-la-paz", title:"AUDIOKISS — la paz suena 24/7", host:"audio.kiss", tags:["music","es","24/7"], viewers:311, mins:412, desc:"Rock urbano y cumbia desde el altiplano. La altura no corta la señal." }),
  G(GLOBAL_FEEDS[2], { id:"ch-012", slug:"13c-santiago", title:"13C CULTURA — señal abierta santiago", host:"tvdigital.cl", tags:["culture","es","documentales"], viewers:1290, mins:640, desc:"Documentales, música y debate del canal cultural chileno. Sin ratings, sin miedo." }),
  G(GLOBAL_FEEDS[3], { id:"ch-013", slug:"agrotendencia-campo", title:"AGROTENDENCIA — el campo costarricense", host:"agro.cr", tags:["campo","es","taller"], viewers:429, mins:233, desc:"Feria del agricultor en vivo: precios honestos, semillas criollas y clima sin intermediarios." }),
  G(GLOBAL_FEEDS[4], { id:"ch-014", slug:"prensa-latina-habana", title:"PRENSA LATINA TV — habana en directo", host:"prensa.latina", tags:["news","es","caribe"], viewers:2211, mins:905, desc:"La agencia de la isla, transmitiendo. Lea contra la corriente y después decida." }),
  G(GLOBAL_FEEDS[5], { id:"ch-015", slug:"a7-jarabacoa", title:"A7 TV JARABACOA — montaña arriba", host:"a7.do", tags:["es","comunidad","montaña"], viewers:287, mins:121, desc:"Televisión comunitaria del confluencia de los ríos. El carnaval se transmite desde la calle." }),
  G(GLOBAL_FEEDS[6], { id:"ch-016", slug:"austral-ecuador", title:"AUSTRAL TV — amazónia abierta", host:"austral.ec", tags:["es","selva","comunidad"], viewers:513, mins:277, desc:"Desde el oriente ecuatoriano: agua, selva y asamblea. Lo que el algoritmo no muestra." }),
  G(GLOBAL_FEEDS[7], { id:"ch-017", slug:"barbe-guatemala", title:"BARBE TV — guatemala city live", host:"barbe.gt", tags:["es","barrio","24/7"], viewers:655, mins:58, desc:"La ciudad vista desde la zona 1. Tertulia, mercado y la festa del barrio sin permiso." }),
  G(GLOBAL_FEEDS[8], { id:"ch-018", slug:"aza-honduras", title:"AZA TV HD — honduras central", host:"aza.hn", tags:["es","comunidad","24/7"], viewers:372, mins:303, desc:"Catrachos al aire: la marcha, el estadio y la cocina de la abuela. Todo junto." }),
  G(GLOBAL_FEEDS[9], { id:"ch-019", slug:"b15-fresnillo", title:"B15 FRESNILLO — zacatecas al aire", host:"b15.mx", tags:["es","frontera","mineros"], viewers:594, mins:812, desc:"La ciudad minera tiene su propia señal. Noticias locales que las cadenas nacionales no tocan." }),
  G(GLOBAL_FEEDS[10], { id:"ch-020", slug:"genios-lima", title:"GENIOS TV — lima pop", host:"genios.pe", tags:["es","juventud","music"], viewers:448, mins:67, desc:"La primera señal adolescente de Perú: quema las reglas de la TV por cable." }),
  G(GLOBAL_FEEDS[11], { id:"ch-021", slug:"america-teve-41", title:"AMERICA TEVE 41 — miami・san juan", host:"amteve.41", tags:["es","en","diáspora"], viewers:1902, mins:1555, desc:"La señal del exilio cubano y el Caribe. Opinión feroz, música vieja, contactos que salvan." }),
  G(GLOBAL_FEEDS[12], { id:"ch-022", slug:"canal-u-uruguay", title:"CANAL U — universidad abierta", host:"canalu.uy", tags:["culture","es","universidad"], viewers:366, mins:820, desc:"El canal de la Universidad de la República: extensión, ciencia y cátedra para quien quiera escuchar." }),
  G(GLOBAL_FEEDS[13], { id:"ch-023", slug:"rivadavia-630", title:"RADIO RIVADAVIA — buenos aires AM630", host:"rivadavia.ar", tags:["radio","news","es"], viewers:1265, mins:2044, desc:"La radio de los taxis porteños. Talk infinito y la sombra de la medianoche." }),
  G(GLOBAL_FEEDS[14], { id:"ch-024", slug:"radio-saudade-99", title:"RÁDIO SAUDADE FM 99.7 — são paulo flashback", host:"saudade.br", tags:["radio","music","pt"], viewers:833, mins:1700, desc:"Hits de ontem tocando agora. Saudade é um formato radiofônico." }),
  G(GLOBAL_FEEDS[15], { id:"ch-025", slug:"olimpica-medellin", title:"OLÍMPICA STEREO — medellín cumbia house", host:"olimpica.co", tags:["radio","music","es"], viewers:721, mins:390, desc:"La salsa, el vallenato y la cumbia que mueven la comuna. La emisora del pueblo paisa." }),
  G(GLOBAL_FEEDS[16], { id:"ch-026", slug:"emisoras-unidas-897", title:"EMISORAS UNIDAS 89.7 — guatemala habla", host:"eunidas.gt", tags:["radio","news","es"], viewers:689, mins:1222, desc:"La radio más escuchada del país: terremotos, elecciones y fútbol. Cobertura que no se apaga." }),
  G(GLOBAL_FEEDS[17], { id:"ch-027", slug:"hrn-la-voz", title:"HRN LA VOZ DE HONDURAS — tegucigalpa", host:"hrn.hn", tags:["radio","news","es"], viewers:402, mins:1500, desc:"Desde 1933 la voz oficial no-oficial del país. El himno suena a las 6 y el pueblo escucha." }),
  G(GLOBAL_FEEDS[18], { id:"ch-028", slug:"cafe-romantico-mty", title:"CAFÉ ROMÁNTICO — monterrey baladas", host:"cafe.mx", tags:["radio","music","es"], viewers:298, mins:2500, desc:"Baladas en español para la sobremesa. Regios nostálgicos, esta es su casa." }),
  G(GLOBAL_FEEDS[19], { id:"ch-029", slug:"planet-1009-panama", title:"PLANET 100.9 — panamá rhythm tv", host:"planet.pa", tags:["music","es","visual radio"], viewers:341, mins:96, desc:"Visual radio panameña: la cumbia del puerto con imagen y todo." }),

  /* ── ÁFRICA ─────────────────────────────────────────── */
  G(GLOBAL_FEEDS[20], { id:"ch-030", slug:"al24-alger", title:"AL24 NEWS — argel wire", host:"al24.dz", tags:["news","ar","fr"], viewers:1622, mins:1110, desc:"La señal joven de la información argelina. El Magreb en directo, 24/7." }),
  G(GLOBAL_FEEDS[21], { id:"ch-031", slug:"filinfo-ouaga", title:"FILINFO TV — burkina pulse", host:"filinfo.bf", tags:["news","fr","sahel"], viewers:277, mins:444, desc:"Noticias continuas de Ouagadougou y el Sahel. Rapidez sobre drama." }),
  G(GLOBAL_FEEDS[22], { id:"ch-032", slug:"cam10-douala", title:"CAM 10 TV — douala downtown", host:"cam10.cm", tags:["fr","comunidad","24/7"], viewers:190, mins:260, desc:"La ciudad portuaria al aire: mercado, música makossa y asambleas vecinales." }),
  G(GLOBAL_FEEDS[23], { id:"ch-033", slug:"alghad-cairo", title:"AL GHAD TV — cairo morning wire", host:"alghad.eg", tags:["news","ar"], viewers:1147, mins:730, desc:"\"Mañana\" en árabe: la señal que despierta con el Nilo. Noticias y debate egipcio." }),
  G(GLOBAL_FEEDS[24], { id:"ch-034", slug:"k24-nairobi", title:"K24 TV — nairobi sin filtro", host:"k24.ke", tags:["en","news","24/7"], viewers:1338, mins:1902, desc:"La señal joven de Nairobi: política, música genge y la ciudad que no duerme." }),
  G(GLOBAL_FEEDS[25], { id:"ch-035", slug:"2m-monde-maghreb", title:"2M MONDE — maghreb abierto", host:"2m.ma", tags:["ar","fr","news"], viewers:2051, mins:3120, desc:"La ventana del Marruecos contemporáneo: series, debate y música del pueblo." }),
  G(GLOBAL_FEEDS[26], { id:"ch-036", slug:"tvm-mozambique", title:"TVM MOZAMBIQUE — mapauto directo", host:"tvm.mz", tags:["pt","news","comunidad"], viewers:356, mins:604, desc:"La tele pública mozambicana: del Índico al Niassa, la señal que llega a la aldea." }),
  G(GLOBAL_FEEDS[27], { id:"ch-037", slug:"nigbati-lagos", title:"NIGBATI TV — lagos culture hour", host:"nigbati.ng", tags:["culture","en","afrobeats"], viewers:499, mins:213, desc:"\"Mi hermano\" en yoruba: cultura de la calle nigeriana, afrobeats y barrio limpio." }),
  G(GLOBAL_FEEDS[28], { id:"ch-038", slug:"tv10-kigali", title:"TV10 KIGALI — rwanda centro", host:"tv10.rw", tags:["en","comunidad","24/7"], viewers:233, mins:95, desc:"Mil colinas, una señal. Cultura, debate y la nueva Rwandan wave." }),
  G(GLOBAL_FEEDS[29], { id:"ch-039", slug:"tele-tchad", title:"TÉLÉ TCHAD — ndjamena antena", host:"tchad.td", tags:["fr","comunidad","sahel"], viewers:154, mins:470, desc:"Chad en directo: sahel, jazz local y los problemas que nadie cubre." }),
  G(GLOBAL_FEEDS[30], { id:"ch-040", slug:"tayari-kampala", title:"TAYARI WEST TV — kampala hoy", host:"tayari.ug", tags:["en","comunidad","24/7"], viewers:262, mins:180, desc:"La Uganda del oeste, transmitida por jóvenes periodistas. Sin intermediarios." }),
  G(GLOBAL_FEEDS[31], { id:"ch-041", slug:"ln24-joburg", title:"LN24 SA — joburg newsroom", host:"ln24.za", tags:["news","en"], viewers:511, mins:340, desc:"Johannesburgo en directo: la economía real, los cortes de luz y la resistencia." }),
  G(GLOBAL_FEEDS[32], { id:"ch-042", slug:"sheger-addis", title:"SHEGER FM 102.1 — addis abeba", host:"sheger.et", tags:["radio","music","am"], viewers:918, mins:1100, desc:"La radio de la capital etíope: jazz etíope, azmari y lo nuevo del barrio." }),
  G(GLOBAL_FEEDS[33], { id:"ch-043", slug:"citi-accra", title:"CITI FM 97.3 — accra newsroom", host:"citi973.gh", tags:["radio","news","en"], viewers:643, mins:890, desc:"El newsroom más respetado de Ghana. Coby y el equipo, en vivo hasta la noche." }),
  G(GLOBAL_FEEDS[34], { id:"ch-044", slug:"hit-radio-maroc", title:"HIT RADIO — casablanca rotation", host:"hit.ma", tags:["radio","music","ar"], viewers:1002, mins:2600, desc:"El hit del Magreb en bucle. Casablanca mueve la cabeza." }),
  G(GLOBAL_FEEDS[35], { id:"ch-045", slug:"zodiak-malawi", title:"ZODIAK FM — malawi nation talk", host:"zodiak.mw", tags:["radio","news","en"], viewers:388, mins:1450, desc:"Radio de servicio público malawiana: los alimentos, el clima y la política del lago." }),
  G(GLOBAL_FEEDS[36], { id:"ch-046", slug:"east-africa-dar", title:"EAST AFRICA RADIO — dar es salaam", host:"ea.fm", tags:["radio","music","sw"], viewers:295, mins:520, desc:"Bongo flava y deporte en la radio costeña. Swahili flow, no filter." }),
  G(GLOBAL_FEEDS[37], { id:"ch-047", slug:"uganda-djs-block", title:"UGANDA DJS — kampala blocks", host:"ugdjs.ug", tags:["radio","music","en"], viewers:201, mins:310, desc:"Hip-hop, rumba y soul desde las torres de Kampala. La mezcla no para." }),
  G(GLOBAL_FEEDS[38], { id:"ch-048", slug:"jacaranda-pretoria", title:"JACARANDA FM — pretoria talk", host:"jacaranda.za", tags:["radio","news","af"], viewers:559, mins:1990, desc:"La radio afrikaans de la capital: charla, tráfico y la vieja canción del jacarandá." }),

  /* ── ASIA ───────────────────────────────────────────── */
  G(GLOBAL_FEEDS[39], { id:"ch-049", slug:"rajdhani-dhaka", title:"RAJDHANI TV — dhaka signal", host:"rajdhani.bd", tags:["bn","news","comunidad"], viewers:477, mins:151, desc:"\"Capital\" en bengalí: la señal local de Dhaka que cubre lo que la nacional olvida." }),
  G(GLOBAL_FEEDS[40], { id:"ch-050", slug:"ardb-camboya", title:"ARDB TV — phnom penh rural", host:"ardb.kh", tags:["km","campo","comunidad"], viewers:133, mins:88, desc:"Rural development TV: arroz, riego y asambleas de aldea. La tele que siembra." }),
  G(GLOBAL_FEEDS[41], { id:"ch-051", slug:"dvb-exile-myanmar", title:"DVB TV — exile news, myanmar", host:"dvb.mm", tags:["my","en","exile"], viewers:1701, mins:4100, desc:"Radio y TV de la resistencia birmana, operada desde el exilio. La señal que el golpe no pudo matar." }),
  G(GLOBAL_FEEDS[42], { id:"ch-052", slug:"kantipur-kathmandu", title:"KANTIPUR TV HD — kathmandu", host:"kantipur.np", tags:["ne","news","24/7"], viewers:812, mins:760, desc:"El Himalaya en HD: el canal privado más visto de Nepal, desde la capital." }),
  G(GLOBAL_FEEDS[43], { id:"ch-053", slug:"bilyonaryo-manila", title:"BILYONARYO NEWS — manila", host:"bilyonaryo.ph", tags:["en","news","negocio"], viewers:394, mins:140, desc:"Periodismo de negocios filipino que sigue el dinero hasta la puerta del poder." }),
  G(GLOBAL_FEEDS[44], { id:"ch-054", slug:"cna-singapore", title:"CNA — singapore wire", host:"cna.sg", tags:["en","news","asia"], viewers:2984, mins:5600, desc:"Channel NewsAsia: la ventana asiática al mundo, sobria y precisa." }),
  G(GLOBAL_FEEDS[45], { id:"ch-055", slug:"siam13-bangkok", title:"13 SIAM THAI — bangkok live", host:"siam13.th", tags:["th","news","24/7"], viewers:289, mins:202, desc:"Bangkok a 1080p: política tailandesa sin el filtro de los generales." }),
  G(GLOBAL_FEEDS[46], { id:"ch-056", slug:"dunyo-tashkent", title:"DUNYO BO'YLAB — tashkent sin fronteras", host:"dunyo.uz", tags:["uz","news","silk road"], viewers:176, mins:125, desc:"\"Por el mundo\" en uzbeko: documentales y viajes por la vieja ruta de la seda." }),
  G(GLOBAL_FEEDS[47], { id:"ch-057", slug:"cantho-mekong", title:"CẦN THƠ TV — mekong delta", host:"cantho.vn", tags:["vi","río","comunidad"], viewers:233, mins:330, desc:"El delta del Mekong en directo: mercados flotantes, lluvia y arroz." }),
  G(GLOBAL_FEEDS[48], { id:"ch-058", slug:"arirang-un-korea", title:"ARIRANG UN — korea global", host:"arirang.kr", tags:["en","news","k-culture"], viewers:1490, mins:7200, desc:"La señal internacional coreana: K-pop, diplomacia y la península explicada." }),
  G(GLOBAL_FEEDS[49], { id:"ch-059", slug:"gugak-arts", title:"GUGAK TV — traditional korean arts", host:"gugak.kr", tags:["music","ko","tradición"], viewers:112, mins:900, desc:"Sanjo, pansori y la orquesta tradicional de Corea. Tres mil años en pantalla." }),
  G(GLOBAL_FEEDS[50], { id:"ch-060", slug:"a2z-dhaka", title:"A2Z RADIO — dhaka waves", host:"a2z.bd", tags:["radio","music","bn"], viewers:167, mins:640, desc:"De todo un poco desde Daca: la playlist que la juventud bengalí comparte." }),
  G(GLOBAL_FEEDS[51], { id:"ch-061", slug:"elshinta-jakarta", title:"ELSHINTA 90FM — jakarta newsline", host:"elshinta.id", tags:["radio","news","id"], viewers:520, mins:3100, desc:"La radio de tráfico y noticias de Yakarta: 24 horas informando la megaciudad." }),
  G(GLOBAL_FEEDS[52], { id:"ch-062", slug:"eurodance-almaty", title:"RADIO 90S EURODANCE — almaty time machine", host:"euro.kz", tags:["radio","music","90s"], viewers:431, mins:2600, desc:"Escuela de eurodance de los 90, transmitida desde Kazajistán. Enciende el VHS." }),
  G(GLOBAL_FEEDS[53], { id:"ch-063", slug:"mandalay-fm", title:"MANDALAY FM — old city air", host:"mandalay.mm", tags:["radio","general","my"], viewers:299, mins:1130, desc:"La segunda ciudad de Myanmar al aire. Música, serene y la voz de la gente." }),
  G(GLOBAL_FEEDS[54], { id:"ch-064", slug:"slow-rock-kl", title:"SLOW ROCK 90S — kuala lumpur ballads", host:"slow.my", tags:["radio","music","en"], viewers:188, mins:1900, desc:"Power ballads sin vergüenza. La memoria radiofónica del sur de Asia." }),
  G(GLOBAL_FEEDS[55], { id:"ch-065", slug:"star-fm-manila", title:"STAR FM MANILA — archipelago pop", host:"starfm.ph", tags:["radio","music","fil"], viewers:246, mins:770, desc:"Pop y love songs para las 7000 islas. La OPM que no sale en las listas." }),
  G(GLOBAL_FEEDS[56], { id:"ch-066", slug:"samaa-karachi", title:"SAMAA FM 107.4 — karachi talk", host:"samaa.pk", tags:["radio","news","ur"], viewers:357, mins:1420, desc:"Talk y actualidad desde la megaciudad portuaria. Samaa: \"cielo\" en urdu." }),
  G(GLOBAL_FEEDS[57], { id:"ch-067", slug:"rfi-vietnam", title:"RFI TIẾNG VIỆT — paris→hanoi", host:"rfi.vn", tags:["radio","news","vi"], viewers:264, mins:2000, desc:"Radio France Internationale en vietnamita. La señal cruzada del estado francés." }),

  /* ── MEDIO ORIENTE ──────────────────────────────────── */
  G(GLOBAL_FEEDS[58], { id:"ch-068", slug:"al-rasheed-baghdad", title:"AL RASHEED — baghdad nights", host:"rasheed.iq", tags:["ar","news","24/7"], viewers:603, mins:880, desc:"La histórica radio-TV iraquí que emitió desde la guerra del Golfo. Bagdad no se calla." }),
  G(GLOBAL_FEEDS[59], { id:"ch-069", slug:"ktv1-kuwait", title:"KTV 1 — kuwait state airwaves", host:"ktv.kw", tags:["ar","news","general"], viewers:229, mins:660, desc:"La señal general kuwaití: series ramadán, debate y la corniche en directo." }),
  G(GLOBAL_FEEDS[60], { id:"ch-070", slug:"aghani-beirut", title:"AGHANI AGHANI — beirut music tv", host:"aghani.lb", tags:["music","ar","24/7"], viewers:341, mins:1050, desc:"\"Canciones, canciones\": el clip libanés sin parar, de Fairuz al dadá electrónico." }),
  G(GLOBAL_FEEDS[61], { id:"ch-071", slug:"al-najah-nablus", title:"AL NAJAH NEWS — nablus student tv", host:"najah.ps", tags:["ar","news","comunidad"], viewers:412, mins:210, desc:"TV de la Universidad An-Najah: estudiantes periodizando Palestina desde Nablus." }),
  G(GLOBAL_FEEDS[62], { id:"ch-072", slug:"al-araby-london", title:"AL ARABY TV — london・doha", host:"alaraby.qa", tags:["ar","news","debate"], viewers:688, mins:1510, desc:"Periodismo árabe independiente desde Londres. El debate que otros evitan." }),
  G(GLOBAL_FEEDS[63], { id:"ch-073", slug:"alarabiya-english", title:"AL ARABIYA ENGLISH — riyadh wire", host:"alarabiya.sa", tags:["en","news","24/7"], viewers:2210, mins:4800, desc:"La versión inglesa del gigante saudí: Medio Oriente en directo, 24/7." }),
  G(GLOBAL_FEEDS[64], { id:"ch-074", slug:"trt-genc-istanbul", title:"TRT GENÇ — estambul joven", host:"trtgenc.tr", tags:["culture","tr","youth"], viewers:393, mins:230, desc:"El canal joven de TRT: música, street food y la Bósforo de noche. 1440p real." }),
  G(GLOBAL_FEEDS[65], { id:"ch-075", slug:"al-masirah-sanaa", title:"AL MASIRAH — sanaa signal", host:"masirah.ye", tags:["ar","news"], viewers:301, mins:1720, desc:"La señal yemení que transmite pese a todo. La guerra vista desde dentro." }),
  G(GLOBAL_FEEDS[66], { id:"ch-076", slug:"amra-tbilisi", title:"RADIO AMRA — tbilisi signal", host:"amra.ge", tags:["radio","music","ka"], viewers:142, mins:510, desc:"\"El sol\" en georgiano: la radio de la vieja ciudad del Cáucaso." }),
  G(GLOBAL_FEEDS[67], { id:"ch-077", slug:"sumer-baghdad", title:"SUMER FM — baghdad rotation", host:"sumer.iq", tags:["radio","music","ar"], viewers:251, mins:990, desc:"Música iraquí sin interrupciones, del maqam al pop de Bagdad." }),
  G(GLOBAL_FEEDS[68], { id:"ch-078", slug:"mazaj-amman", title:"MAZAJ FM — amman 192k", host:"mazaj.jo", tags:["radio","music","ar"], viewers:173, mins:400, desc:"\"Mood\" en árabe: la radio joven de Amán, puro flow jordano." }),
  G(GLOBAL_FEEDS[69], { id:"ch-079", slug:"sawtlebnan-beirut", title:"VOICE OF LEBANON 93.3 — beirut", host:"sawt.lb", tags:["radio","general","ar"], viewers:284, mins:2340, desc:"Sawtlebnan: la voz del cedro. Charla, paloma y música que atraviesa la crisis." }),

  /* ── EUROPA ─────────────────────────────────────────── */
  G(GLOBAL_FEEDS[70], { id:"ch-080", slug:"atv-antwerpen", title:"ATV ANTWERPEN — puerto franco", host:"atv.be", tags:["nl","local","comunidad"], viewers:201, mins:150, desc:"La tele local de Amberes: el puerto, los barrios y el carnaval flamenco." }),
  G(GLOBAL_FEEDS[71], { id:"ch-081", slug:"current-time-prague", title:"CURRENT TIME TV — prag wire", host:"currenttime.cz", tags:["ru","en","news"], viewers:876, mins:3300, desc:"Periodismo en ruso operado desde Praga. La señal libre para la post-URSS." }),
  G(GLOBAL_FEEDS[72], { id:"ch-082", slug:"dr1-copenhagen", title:"DR1 — copenhagen public air", host:"dr.dk", tags:["da","news","público"], viewers:1102, mins:7200, desc:"La cadena pública danesa: drama nórdico y el mejor service público del planeta." }),
  G(GLOBAL_FEEDS[73], { id:"ch-083", slug:"nopola-tampere", title:"NOPOLA NEWS — tampere local", host:"nopola.fi", tags:["fi","local","news"], viewers:94, mins:60, desc:"Periodismo hiperlocal finlandés: el pueblo de Tampere, cubierto a fondo." }),
  G(GLOBAL_FEEDS[74], { id:"ch-084", slug:"20minutes-paris", title:"20 MINUTES TV — paris rápido", host:"20min.fr", tags:["fr","news","free"], viewers:703, mins:280, desc:"La tele del diario gratuito: París en 20 minutos, sin papeleo." }),
  G(GLOBAL_FEEDS[75], { id:"ch-085", slug:"alpha-athens", title:"ALPHA TV — atenas directo", host:"alpha.gr", tags:["el","general","24/7"], viewers:487, mins:1600, desc:"La privada griega de referencia: debate feroz y la isla de moda en verano." }),
  G(GLOBAL_FEEDS[76], { id:"ch-086", slug:"cmc-croatia", title:"CMC TV — croatian music channel", host:"cmc.hr", tags:["music","hr","24/7"], viewers:132, mins:400, desc:"Música croata sin parar: el Adriático en formato videoclip." }),
  G(GLOBAL_FEEDS[77], { id:"ch-087", slug:"1twente-regional", title:"1TWENTE — twente regional", host:"1twente.nl", tags:["nl","local","comunidad"], viewers:88, mins:90, desc:"La tele de la región de Twente: molinos, fútbol amateur y asambleas vecinales." }),
  G(GLOBAL_FEEDS[78], { id:"ch-088", slug:"tv-ostfold", title:"TV ØSTFOLD — fredrikstad", host:"ostfold.no", tags:["no","local","comunidad"], viewers:121, mins:74, desc:"Noruega local: el condado de Østfold cubierto por gente del condado." }),
  G(GLOBAL_FEEDS[79], { id:"ch-089", slug:"artv-lisboa", title:"ARTV — parlamento portugués", host:"artv.pt", tags:["legislative","pt","público"], viewers:177, mins:5300, desc:"Las Cortes portuguesas en directo. La democracia sin filtro y sin cortes." }),
  G(GLOBAL_FEEDS[80], { id:"ch-090", slug:"a7tv-bucarest", title:"A7TV — bucarest abierta", host:"a7tv.ro", tags:["ro","comunidad","debate"], viewers:243, mins:350, desc:"Televisión comunitaria rumana: debate, iglesia, barrio y contrapoder." }),
  G(GLOBAL_FEEDS[81], { id:"ch-091", slug:"di-tv-stockholm", title:"DI TV — stockholm wire", host:"ditv.se", tags:["sv","news","negocio"], viewers:359, mins:190, desc:"La tele del Dagens industriell: mercados nórdicos y la economía real sueca." }),
  G(GLOBAL_FEEDS[82], { id:"ch-092", slug:"radio-svoboda", title:"РАДИО СВОБОДА — prague exile frequency", host:"svoboda.cz", tags:["radio","news","ru"], viewers:623, mins:4100, desc:"Radio Liberty en ruso, transmitida desde Chequia. Palabra contra propaganda." }),
  G(GLOBAL_FEEDS[83], { id:"ch-093", slug:"los40-madrid", title:"LOS40 ESPAÑA — madrid chart", host:"los40.es", tags:["radio","music","es"], viewers:512, mins:6100, desc:"La lista del 40 principal: la radio pop que sonó en la rebajas y en el botellón." }),
  G(GLOBAL_FEEDS[84], { id:"ch-094", slug:"zeppelin-athens", title:"ZEPPELIN 106.7 — athens rock", host:"zeppelin.gr", tags:["radio","music","rock"], viewers:219, mins:1400, desc:"Rock clásico y moderno desde la ERT pública griega. Vuela sobre la Acrópolis." }),
  G(GLOBAL_FEEDS[85], { id:"ch-095", slug:"dancewave-budapest", title:"DANCE WAVE! — budapest club", host:"dancewave.hu", tags:["radio","music","electronic"], viewers:384, mins:2900, desc:"Trance y house sin parar desde el Danubio. El after que nunca cierra." }),
  G(GLOBAL_FEEDS[86], { id:"ch-096", slug:"rfm-lisboa", title:"RFM — lisboa pop", host:"rfm.pt", tags:["radio","music","pt"], viewers:297, mins:2500, desc:"La emisora más escuchada de Portugal: pop, saudade y el top del momento." }),
  G(GLOBAL_FEEDS[87], { id:"ch-097", slug:"radio-vanya", title:"РАДИО ВАНЯ — moscow pop wire", host:"vanya.ru", tags:["radio","music","ru"], viewers:331, mins:3300, desc:"Pop ruso 24/7: la banda sonora de los minibuses de Moscú." }),

  /* ── NORTeamérica ───────────────────────────────────── */
  G(GLOBAL_FEEDS[88], { id:"ch-098", slug:"accuweather-now", title:"ACCUWEATHER NOW — sky alarm", host:"accu.us", tags:["weather","en","24/7"], viewers:666, mins:9999, desc:"El cielo en directo: huracanes, tormentas y el clima que decide cosechas y marchas." }),
  G(GLOBAL_FEEDS[89], { id:"ch-099", slug:"akaku-53-maui", title:"AKAKU 53 MAUI — community access hawai'i", host:"akaku.org", tags:["access","en","pacífico"], viewers:147, mins:800, desc:"Pūngāwa: la tele pública de Maui. Lo que la comunidad quiere emitir, se emite." }),
  G(GLOBAL_FEEDS[90], { id:"ch-100", slug:"akaku-55-maui", title:"AKAKU 55 MAUI — molokai・lana'i", host:"akaku55.org", tags:["access","en","pacífico"], viewers:96, mins:1500, desc:"El canal hermano: las islas vecinas, sus escuelas y sus ceremonias, en directo." }),
  G(GLOBAL_FEEDS[91], { id:"ch-101", slug:"aftv-framingham", title:"AFTV FRAMINGHAM — access tv massachusetts", host:"aftv.us", tags:["access","en","brasil"], viewers:74, mins:220, desc:"Public access de Framingham, MA: la comunidad brasileña local tiene su propia hora." }),
  G(GLOBAL_FEEDS[92], { id:"ch-102", slug:"az-star-toronto", title:"AZ STAR TV — toronto suburbia", host:"azstar.ca", tags:["en","comunidad","24/7"], viewers:165, mins:370, desc:"La tele de la diáspora del sur de Asia en Toronto: música, fe y barrio." }),
  G(GLOBAL_FEEDS[93], { id:"ch-103", slug:"cfru-guelph", title:"CFRU 93.3 GUELPH — campus air", host:"cfru.ca", tags:["radio","community","en"], viewers:88, mins:460, desc:"Radio campus de la University of Guelph: freeform, jazz, y comunidad real." }),
  G(GLOBAL_FEEDS[94], { id:"ch-104", slug:"kgnu-boulder", title:"KGNU 88.5 BOULDER — freeform mountain air", host:"kgnu.org", tags:["radio","community","en"], viewers:154, mins:7300, desc:"Listener-run desde 1968. Sin consultores, sin anuncios: la montaña habla." }),
  G(GLOBAL_FEEDS[95], { id:"ch-105", slug:"wfmu-freeform", title:"WFMU 91.1 — the freeform mothership", host:"wfmu.org", tags:["radio","community","en"], viewers:521, mins:9500, desc:"La emisora libre por excelencia desde Jersey City. DJs con permiso total para arruinar tu género favorito." }),

  /* ── OCEANÍA ────────────────────────────────────────── */
  G(GLOBAL_FEEDS[96], { id:"ch-106", slug:"abc-news-au", title:"ABC NEWS AUSTRALIA — sydney wire", host:"abc.net.au", tags:["en","news","público"], viewers:977, mins:5400, desc:"La cadena pública australiana: incendios, océano y la política de Canberra." }),
  G(GLOBAL_FEEDS[97], { id:"ch-107", slug:"ticker-melbourne", title:"TICKER NEWS — melbourne markets", host:"ticker.au", tags:["en","news","negocio"], viewers:203, mins:310, desc:"Noticias de negocio y actualidad australiana, estilo wire. Rapidito." }),
  G(GLOBAL_FEEDS[98], { id:"ch-108", slug:"nz-parliament-tv", title:"NZ PARLIAMENT TV — wellington debates", host:"ptv.nz", tags:["legislative","en","público"], viewers:118, mins:6100, desc:"La cámara neozelandesa en directo: preguntas sin guion y el haka de los debates." }),
  G(GLOBAL_FEEDS[99], { id:"ch-109", slug:"nbc-papua", title:"NBC PNG — papua new guinea", host:"nbc.pg", tags:["en","tok pisin","comunidad"], viewers:137, mins:170, desc:"La radiotelevisión nacional de PNG: la señal de las mil lenguas." }),
  G(GLOBAL_FEEDS[100], { id:"ch-110", slug:"3cr-melbourne", title:"3CR 855AM MELBOURNE — community strike frequency", host:"3cr.org.au", tags:["radio","community","activismo"], viewers:129, mins:8300, desc:"Desde 1976: la radio de los movimientos australianos. 140 programas en lenguas del mundo." }),
];
/* ---- ALT-WAVE: the undial ----
   legendary free/pirate/community/campus/anarchist stations.
   every URL verified flowing https audio bytes 2026-09 (12-32KB pulled).
   regional gates killed: NTS 1, KXLU, KFJC, KBOO, KPFK-via-cert, CFRO, Radio Libertaire —
   kept only what actually streams from a browser. */
const ALT_FEEDS = [
  { id:"a-canut",        cc:"FR", kind:"radio", label:"FR · RADIO CANUT",        url:"https://live.aurafm.org/radiocanut" },
  { id:"a-zinzine",      cc:"FR", kind:"radio", label:"FR · RADIO ZINCINE",      url:"https://stream.radiozinzine.org:8443/3" },
  { id:"a-dreyeckland",  cc:"DE", kind:"radio", label:"DE · RADIO DREYECKLAND",  url:"https://stream.rdl.de/rdl" },
  { id:"a-corax",        cc:"DE", kind:"radio", label:"DE · RADIO CORAX",        url:"https://streaming.fueralle.org/corax_192.mp3" },
  { id:"a-fsk",          cc:"DE", kind:"radio", label:"DE · FSK HAMBURG",        url:"https://streaming.fueralle.org/fsk.ogg" },
  { id:"a-student",      cc:"SI", kind:"radio", label:"SI · RADIO STUDENT",      url:"https://kruljo.radiostudent.si:8001/hiq" },
  { id:"a-o94",          cc:"AT", kind:"radio", label:"AT · ORANGE 94.0",        url:"https://securestream.o94.at/live.mp3" },
  { id:"a-helsinki",     cc:"AT", kind:"radio", label:"AT · RADIO HELSINKI",     url:"https://live.helsinki.at:8088/live160.mp3" },
  { id:"a-resonance",    cc:"GB", kind:"radio", label:"GB · RESONANCE 104.4FM",  url:"https://stream.resonance.fm/resonance?rp_source=1&=&&___cb=309691324386261" },
  { id:"a-res-extra",    cc:"GB", kind:"radio", label:"GB · RESONANCE EXTRA",    url:"https://stream.resonance.fm/resonance-extra" },
  { id:"a-rinse",        cc:"GB", kind:"radio", label:"GB · RINSE FM",           url:"https://admin.stream.rinse.fm/proxy/rinse_uk/stream" },
  { id:"a-worldwide",    cc:"GB", kind:"radio", label:"GB · WORLDWIDE FM",       url:"https://worldwide-fm.radiocult.fm/stream" },
  { id:"a-dublab-bcn",   cc:"ES", kind:"radio", label:"ES · DUBLAB BCN",         url:"https://dublabbcn.out.airtime.pro/dublabbcn_a" },
  { id:"a-kpfa",         cc:"US", kind:"radio", label:"US · KPFA BERKELEY",      url:"https://streams.kpfa.org:8443/kpfa" },
  { id:"a-wbai",         cc:"US", kind:"radio", label:"US · WBAI NEW YORK",      url:"https://stream.wbai.org/wbai_128.mp3" },
  { id:"a-kpfk",         cc:"US", kind:"radio", label:"US · KPFK LOS ANGELES",   url:"https://stream.kpfk.org/kpfk_128.mp3" },
  { id:"a-wwoz",         cc:"US", kind:"radio", label:"US · WWOZ NEW ORLEANS",   url:"https://wwoz-sc.streamguys1.com/wwozhd2-hi" },
  { id:"a-wort",         cc:"US", kind:"radio", label:"US · WORT MADISON",       url:"https://wortcast01.wortfm.org:8443/high.mp3" },
  { id:"a-kvrx",         cc:"US", kind:"radio", label:"US · KVRX AUSTIN",        url:"https://kvrx.org/now_playing/stream" },
  { id:"a-kzsc",         cc:"US", kind:"radio", label:"US · KZSC SANTA CRUZ",    url:"https://kzscfms1-geckohost.radioca.st/kzschigh" },
  { id:"a-rfb",          cc:"US", kind:"radio", label:"US · RADIO FREE BROOKLYN",url:"https://patmos.cdnstream.com/proxy/ttenney1/?mp=/listen&esPlayer&cb=239941.mp3" },
  { id:"a-dublab-la",    cc:"US", kind:"radio", label:"US · DUBLAB LOS ANGELES", url:"https://dublab.out.airtime.pro/dublab_a" },
  { id:"a-chirp",        cc:"US", kind:"radio", label:"US · CHIRP RADIO",        url:"https://peridot.streamguys1.com:5185/live" },
  { id:"a-wavefarm",     cc:"US", kind:"radio", label:"US · WAVE FARM WGXC",     url:"https://audio.wavefarm.org/pondstation.mp3" },
  { id:"a-cfrc",         cc:"CA", kind:"radio", label:"CA · CFRC KINGSTON",      url:"https://audio.cfrc.ca/stream" },
  { id:"a-cjly",         cc:"CA", kind:"radio", label:"CA · KOOTENAY CO-OP",     url:"https://relay1.cjly.net/64" },
  { id:"a-latribu",      cc:"AR", kind:"radio", label:"AR · FM LA TRIBU",        url:"https://icecast.zeclogiccloud.com.de/fmlatribu" },
  { id:"a-mania",        cc:"PT", kind:"radio", label:"PT · RADIO MANIA",        url:"https://radiomania.stream.laut.fm/radiomania" },
  { id:"a-alhara",       cc:"PS", kind:"radio", label:"PS · RADIO ALHARA",       url:"https://n10.radiojar.com/8s5u5tpdtwzuv" },
  { id:"a-mellotron",    cc:"FR", kind:"radio", label:"FR · LE MELLOTRON",       url:"https://listen.radioking.com/radio/477719/stream/534044" },
];

/* ALT-WAVE channel builder: stream + provenance + the story it carries */
const A = (feed, o) => ({
  id: o.id,
  slug: o.slug,
  title: o.title,
  host: o.host,
  tags: o.tags,
  live: true,
  viewers: o.viewers,
  stream: feed,
  thumb: `https://picsum.photos/seed/${o.slug}/640/360`,
  started: Date.now() - o.mins * 60000,
  desc: o.desc,
  cc: feed.cc,
  country: COUNTRY_NAMES[feed.cc] || feed.cc,
  alt: true,
});

const ALT_CHANNELS = [
  /* Europa libre */
  A(ALT_FEEDS[0],  { id:"ch-111", slug:"radio-canut-lyon", title:"RADIO CANUT 102.2 — lyon lutte fm", host:"canut.frr", tags:["free radio","fr","canut"], viewers:143, mins:4240, desc:"Née en 1977 des luttes des canuts. Les pirates ont été arrêtés — l'onde est restée." }),
  A(ALT_FEEDS[1],  { id:"ch-112", slug:"radio-zinzine-haute-provence", title:"RADIO ZINCINE 98.2 — sainte-croix", host:"zinzine.fr", tags:["free radio","fr","1977"], viewers:121, mins:2810, desc:"La Grand'Maison: oasis libertaire et studios. Quarante ans d'onde verte." }),
  A(ALT_FEEDS[2],  { id:"ch-113", slug:"dreyeckland-freiburg", title:"RADIO DREYECKLAND — freiburg anti-nuke air", host:"rdl.de", tags:["free radio","de","anti-nuke"], viewers:132, mins:4200, desc:"Née des marches anti-nucléaire de Wyhl en 1977, exilée, revenue. Antifaschistisches Radio." }),
  A(ALT_FEEDS[3],  { id:"ch-114", slug:"radio-corax-halle", title:"RADIO CORAX 95.9 — halle freies radio", host:"corax.de", tags:["free radio","de","ost"], viewers:97, mins:2450, desc:"Postsovjetisches Freies Radio — dans l'ex-RDA, l'antenne libre qui reste." }),
  A(ALT_FEEDS[4],  { id:"ch-115", slug:"fsk-hamburg", title:"FSK 92.4 — freies sender kombinat", host:"fsk-hh.de", tags:["free radio","de","hamburg"], viewers:88, mins:1560, desc:"Le combinat libre de Hambourg depuis 1988: libre antenne, pièces audio, posters sonores." }),
  A(ALT_FEEDS[5],  { id:"ch-116", slug:"radio-student-ljubljana", title:"RADIO STUDENT — ljubljana since 1958", host:"student.si", tags:["free radio","si","1958"], viewers:203, mins:9600, desc:"L'un des plus vieux free radios d'Europe, né à l'université de Ljubljana en 1958." }),
  A(ALT_FEEDS[6],  { id:"ch-117", slug:"orange-94-wien", title:"ORANGE 94.0 — wien freies radio", host:"o94.at", tags:["free radio","de","wien"], viewers:118, mins:5200, desc:"La maison-mère des free radios autrichiennes depuis 1998. Quatre quarts de liberté." }),
  A(ALT_FEEDS[7],  { id:"ch-118", slug:"radio-helsinki-graz", title:"RADIO HELSINKI 107.5 — graz", host:"helsinki.at", tags:["free radio","de","steiermark"], viewers:102, mins:3900, desc:"Freies Radio Graz: ateliers ouverts, podcasts, et l'antenne qui fait tourner les gens." }),
  /* Península */
  A(ALT_FEEDS[8],  { id:"ch-122", slug:"resonance-1044-london", title:"RESONANCE 104.4FM — london art-air", host:"resonancefm", tags:["art radio","en","104.4"], viewers:167, mins:7800, desc:"Depuis 2002, l'art du son 24/7 — the laziest radio station in the universe." }),
  A(ALT_FEEDS[9],  { id:"ch-123", slug:"resonance-extra-london", title:"RESONANCE EXTRA — longform ether", host:"resonanceextra", tags:["art radio","en","longform"], viewers:73, mins:3300, desc:"La sœur longform: programmes démesurés, expérimentaux, sans horaire raisonnable." }),
  A(ALT_FEEDS[10], { id:"ch-124", slug:"rinse-fm-london", title:"RINSE FM — london underground lineage", host:"rinse.fm", tags:["pirate","en","grime"], viewers:412, mins:11000, desc:"Née pirate dans les towers de Londres: grime, dubstep, garage. L'onde qui a fait danser le royaume." }),
  A(ALT_FEEDS[11], { id:"ch-125", slug:"worldwide-fm-globe", title:"WORLDWIDE FM — global sound system", host:"worldwide.fm", tags:["music","en","worldwide"], viewers:154, mins:2900, desc:"Le réseau de Gilles Peterson: jazz brésilien, cumbia londonienne, everything worldwide." }),
  A(ALT_FEEDS[12], { id:"ch-126", slug:"dublab-bcn", title:"DUBLAB BCN — deep listening barcelona", host:"dublab.es", tags:["freeform","es","music"], viewers:81, mins:1400, desc:"L'antenne barcelonaise du collectif dublab: deep listening, future roots." }),
  /* Pacifica & the states */
  A(ALT_FEEDS[13], { id:"ch-127", slug:"kpfa-berkeley", title:"KPFA 94.1 — berkeley pacifica", host:"pacifica.org", tags:["pirate","en","pacifica"], viewers:301, mins:9999, desc:"La première radio listener-sponsored de l'histoire (1949), née pirate." }),
  A(ALT_FEEDS[14], { id:"ch-128", slug:"wbai-new-york", title:"WBAI 99.5 — new york free speech", host:"pacifica.org", tags:["community","en","free speech"], viewers:186, mins:8400, desc:"La cinquième Pacifica: radio libre de New York depuis 1960 — critiques, poésie, lutte." }),
  A(ALT_FEEDS[15], { id:"ch-129", slug:"kpfk-la", title:"KPFK 90.7 — los angeles pacifica", host:"pacifica.org", tags:["community","en","pacifica"], viewers:142, mins:7700, desc:"Pacifica Los Angeles: folk, radio drama et journalisme militante sur l'onde de 90.7." }),
  A(ALT_FEEDS[16], { id:"ch-130", slug:"wwoz-new-orleans", title:"WWOZ 90.7 — new orleans tradition", host:"wwoz.org", tags:["community","en","jazz"], viewers:229, mins:6800, desc:"Jazz & Heritage: la radio qui garde vivant le son de la Nouvelle-Orléans." }),
  A(ALT_FEEDS[17], { id:"ch-131", slug:"wort-madison", title:"WORT 89.9 — madison volunteer air", host:"wortfm.org", tags:["community","en","volunteer"], viewers:97, mins:4500, desc:"Les radios de voisinage: WORT, 100% bénévole depuis 1975." }),
  A(ALT_FEEDS[18], { id:"ch-132", slug:"kvrx-austin", title:"KVRX 91.7 — austin student freeform", host:"utexas.edu", tags:["campus","en","freeform"], viewers:84, mins:2600, desc:"None of the above: le freeform étudiant d'Austin qui refuse les formats." }),
  A(ALT_FEEDS[19], { id:"ch-133", slug:"kzsc-santa-cruz", title:"KZSC 88.1 — santa cruz surf rock", host:"ucsc.edu", tags:["campus","en","surf"], viewers:76, mins:1800, desc:"La voix des étudiants de Santa Cruz: surf, folk et expérimentations." }),
  A(ALT_FEEDS[20], { id:"ch-134", slug:"radio-free-brooklyn", title:"RADIO FREE BROOKLYN — internet pirate", host:"rfb.nyc", tags:["internet radio","en","brooklyn"], viewers:112, mins:2000, desc:"Plus de cent shows d'artistes et de DJ de Brooklyn, en ligne depuis 2016." }),
  A(ALT_FEEDS[21], { id:"ch-135", slug:"dublab-la", title:"DUBLAB LA — future roots los angeles", host:"dublab.com", tags:["freeform","en","future roots"], viewers:129, mins:5900, desc:"Le collectif dublab d'origine: freeform, future roots, esthétique du possible." }),
  A(ALT_FEEDS[22], { id:"ch-136", slug:"chirp-chicago", title:"CHIRP RADIO — chicago people's air", host:"chirpradio.org", tags:["community","en","chicago"], viewers:91, mins:3100, desc:"Volunteer-powered Chicago: la playlist que les radios commerciales ne touchent pas." }),
  A(ALT_FEEDS[23], { id:"ch-137", slug:"wave-farm-hudson", title:"WAVE FARM WGXC 90.7 — hudson ny", host:"wavefarm.org", tags:["art radio","en","transmission art"], viewers:68, mins:2400, desc:"L'art de la transmission comme discipline: l'onde comme matériau." }),
  A(ALT_FEEDS[24], { id:"ch-138", slug:"cfrc-kingston", title:"CFRC 101.9 — kingston campus since 1922", host:"cfrc.ca", tags:["campus","en","1922"], viewers:71, mins:9400, desc:"Depuis 1922: l'une des plus vieilles radios campus au monde." }),
  A(ALT_FEEDS[25], { id:"ch-139", slug:"cjly-kootenay", title:"KOOTENAY CO-OP RADIO 93.5 — nelson bc", host:"cjly.net", tags:["community","en","coop"], viewers:59, mins:3600, desc:"Coopérative de la montagne: Nelson BC, l'onde des vallées." }),
  /* The south & the field */
  A(ALT_FEEDS[26], { id:"ch-140", slug:"fm-la-tribu-887", title:"FM LA TRIBU 88.7 — buenos aires colectiva", host:"latribu.org.ar", tags:["free radio","es","colectiva"], viewers:198, mins:6100, desc:"Radio colectiva porteña desde 1989: autogestión, música y asamblea." }),
  A(ALT_FEEDS[27], { id:"ch-141", slug:"radio-mania-coimbra", title:"RADIO MANIA — coimbra alternativa", host:"radiomania.pt", tags:["free radio","pt","coimbra"], viewers:63, mins:1900, desc:"La radio alternative de Coimbra: regueifa, punk e livre antena." }),
  A(ALT_FEEDS[28], { id:"ch-142", slug:"radio-alhara-bethlehem", title:"RADIO ALHARA — bethlehem → world", host:"alhara.radio", tags:["freeform","ps","palestine"], viewers:351, mins:4200, desc:"Née à Bethlehem en 2020: the pulse of palestine — collective, solidaire, worldwide." }),
  A(ALT_FEEDS[29], { id:"ch-143", slug:"le-mellotron-marseille", title:"LE MELLOTRON — marseille music atlas", host:"lemellotron.com", tags:["music","fr","web radio"], viewers:94, mins:2300, desc:"Web radio marseillaise: jazz-funk-brésil-grooves — l'atlas musical du port." }),
];

/* mount the undial onto the live register */
CHANNELS.push(...ALT_CHANNELS);

